import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Proposifly",
  description: "Read the terms and conditions for using Proposifly, the free AI proposal and PRD generator.",
};

const sections = [
  {
    title: "1. Acceptance of Terms",
    text: "By accessing or using Proposifly, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.",
  },
  {
    title: "2. Description of Service",
    text: "Proposifly is a free AI-powered platform that helps freelancers create professional proposals and Project Requirements Documents (PRDs). The service includes proposal generation with multiple tones, auto-attachment of portfolio and profile links, proposal history with search and filters, and PRD generation with customizable phases, budget, timeline, and tools. The service is provided as-is and may be updated or modified at any time.",
  },
  {
    title: "3. User Accounts",
    text: "You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information when creating an account, including your name which will be used to sign your proposals. You are responsible for all activity that occurs under your account.",
  },
  {
    title: "4. Acceptable Use",
    text: "You agree not to use Proposifly for any unlawful purpose, to generate spam or misleading content, to attempt to gain unauthorized access to the service, or to interfere with the proper functioning of the platform.",
  },
  {
    title: "5. AI-Generated Content",
    text: "Proposals and PRDs generated by Proposifly are created using third-party AI models. We do not guarantee the accuracy, quality, or suitability of generated content. You are solely responsible for reviewing and editing proposals and PRDs before sending them to clients.",
  },
  {
    title: "6. Intellectual Property",
    text: "You retain ownership of your portfolio links, profile information, and any content you input. Proposals and PRDs generated through the service are yours to use freely. The Proposifly brand, logo, and website design are owned by us.",
  },
  {
    title: "7. Data and History",
    text: "Generated proposals are automatically saved to your account history. You can view, search, filter, and delete your proposals at any time. Deleting a proposal will also remove any associated PRDs.",
  },
  {
    title: "8. Limitation of Liability",
    text: 'Proposifly is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the service, including but not limited to lost revenue, data loss, or business interruption.',
  },
  {
    title: "9. Termination",
    text: "We reserve the right to suspend or terminate your account at any time for violation of these terms. You may delete your account at any time through the Settings page.",
  },
  {
    title: "10. Changes to Terms",
    text: "We may update these Terms of Service from time to time. Continued use of the service after changes constitutes acceptance of the updated terms.",
  },
  {
    title: "11. Contact",
    text: "If you have any questions about these Terms, please contact us at support@proposifly.app.",
  },
];

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12 space-y-6 relative">
      {/* Background glow */}
      <div className="absolute inset-0 pointer-events-none -z-10">
        <div className="absolute top-20 left-1/4 w-[400px] h-[400px] bg-vscode-primary/5 rounded-full blur-3xl" />
      </div>

      {/* Header */}
      <div className="glass rounded-2xl p-8 border border-vscode-border/50 text-center">
        <div className="inline-flex items-center justify-center w-12 h-12 rounded-xl bg-vscode-primary/10 border border-vscode-primary/20 mb-3">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-vscode-primary"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6"/><path d="M16 13H8"/><path d="M16 17H8"/><path d="M10 9H8"/></svg>
        </div>
        <h1 className="text-3xl font-bold text-vscode-heading mb-1">Terms of Service</h1>
        <p className="text-vscode-text-muted text-sm">Last updated: April 2025</p>
      </div>

      {/* Sections */}
      {sections.map((s, i) => (
        <div key={i} className="glass rounded-2xl p-6 border border-vscode-border/50">
          <h2 className="text-lg font-semibold text-vscode-heading mb-3">{s.title}</h2>
          <p className="text-vscode-text leading-relaxed text-sm">{s.text}</p>
        </div>
      ))}
    </div>
  );
}
