import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Proposifly",
  description: "Read the terms and conditions for using Proposifly, the free AI proposal generator.",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12 space-y-8">
      <h1 className="text-3xl font-bold text-white">Terms of Service</h1>
      <p className="text-vscode-text-muted text-sm">Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">1. Acceptance of Terms</h2>
        <p className="text-vscode-text leading-relaxed">
          By accessing or using Proposifly, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">2. Description of Service</h2>
        <p className="text-vscode-text leading-relaxed">
          Proposifly is a free AI-powered proposal generator that helps freelancers create professional proposals by analyzing job descriptions and attaching portfolio links. The service is provided as-is and may be updated or modified at any time.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">3. User Accounts</h2>
        <p className="text-vscode-text leading-relaxed">
          You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information when creating an account. You are responsible for all activity that occurs under your account.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">4. Acceptable Use</h2>
        <p className="text-vscode-text leading-relaxed">
          You agree not to use Proposifly for any unlawful purpose, to generate spam or misleading content, to attempt to gain unauthorized access to the service, or to interfere with the proper functioning of the platform.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">5. AI-Generated Content</h2>
        <p className="text-vscode-text leading-relaxed">
          Proposals generated by Proposifly are created using third-party AI models. We do not guarantee the accuracy, quality, or suitability of generated content. You are solely responsible for reviewing and editing proposals before sending them to clients.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">6. Intellectual Property</h2>
        <p className="text-vscode-text leading-relaxed">
          You retain ownership of your portfolio links, profile information, and any content you input. Proposals generated through the service are yours to use freely. The Proposifly brand, logo, and website design are owned by us.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">7. Limitation of Liability</h2>
        <p className="text-vscode-text leading-relaxed">
          Proposifly is provided &ldquo;as is&rdquo; without warranties of any kind. We are not liable for any damages arising from your use of the service, including but not limited to lost revenue, data loss, or business interruption.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">8. Termination</h2>
        <p className="text-vscode-text leading-relaxed">
          We reserve the right to suspend or terminate your account at any time for violation of these terms. You may delete your account at any time through the Settings page.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">9. Changes to Terms</h2>
        <p className="text-vscode-text leading-relaxed">
          We may update these Terms of Service from time to time. Continued use of the service after changes constitutes acceptance of the updated terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">10. Contact</h2>
        <p className="text-vscode-text leading-relaxed">
          If you have any questions about these Terms, please contact us at support@proposifly.app.
        </p>
      </section>
    </div>
  );
}
